#! /bin/bash
root_dir="$HOME/.config/piebar"
. ${root_dir}/colors

monitor_count=$(bspc query -M | wc -l)

while read -r line ; do
  case $line in
    C*)
      clock="[%{F$COLORS_CLOCK_FOREGROUND$}${line#?}%{F-}]"
      ;;
    T*)
      title="${line#?}"
      ;;
#    M*)
#      music=""
#      IFS=":"
#      set -- ${line#?}
#      while [ $# -gt 0 ] ; do
#        item=$1
#        name=${item#?}
#        case $item in
#          A*)
#            artist="${name#?}"
#            ;;
#          T*)
#            track="${name#?}"
#            ;;
#        esac
#        music="$artist - $track"
#      done
#      unset IFS
#      ;;
    W*)
      wm_infos=""
      IFS=":"
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          O*)
            wm_infos="${wm_infos}%{F$COLORS_FOREGROUND_DESKTOP_ACTIVE} [${name}] %{F-}"
            ;;
          f*)
            wm_infos="${wm_infos}%{B$COLORS_BACKGROUND_DESKTOP_INACTIVE}  ${name}  %{B-}"
            ;;
          u*)
            wm_infos="${wm_infos}%{B$COLORS_BACKGROUND_DESKTOP_INACTIVE}  ${name}  %{B-}"
            ;;
          o*)
            wm_infos="${wm_infos}%{B$COLORS_BACKGROUND_DESKTOP_INACTIVE}  ${name}  %{B-}"
            ;;
          L*)
            ;;
        esac
        shift
      done
      unset IFS
      ;;
  esac
  printf "%s\n" "%{l}$wm_infos%{c}$title%{r}$music  $clock  "
done
